tests:
  image: registry.gitlab.com/axolotl1/axolotl/base:latest
  stage: test
  tags:
    - d3m_runner
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - pip3 install -e .
    - python3 ./run_tests.py


build_base_image:
  stage: build
  image: registry.gitlab.com/datadrivendiscovery/images/testing:ubuntu-bionic-python36
  tags:
    - d3m_runner
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - ./images/build-images.sh base
  only:
    - devel



